name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig: [ 0.9.0, master]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: ${{ matrix.zig }}
      - run: zig version
      - run: zig env
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod ci
      - run: zig build test
      - run: zig build
      - run: cp zig-out/bin/skip .
      - run: ./test.sh
